name: Example Running Python File in Github Actions 
on:
  workflow_dispatch:
    
jobs:
  py-training:
    runs-on: [ubuntu-latest]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Set up Python 3.11.0
        uses: actions/setup-python@v4 # Github action which setups python env 
        with:
          python-version: "3.11"
        
      - name: Install Python dependencies # Execute shell script to Install Dependencies
        run: |
         python3 --version
         python3 -m pip install --upgrade pip
         pip install art
     

      - name: Run Python Script
        run: |
          python3 "Python_Lessons/10_Modules&Pip/03_Install_Packages_with_Pip.py"
          
         
     
          
          
    
       

      
